version: "3"

services:
  webserver:
    build: 
      context: ./bin/webserver
    container_name: 'affilate-webserver'
    restart: 'always'
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
    links: 
      - pgsql
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
  pgsql:
    container_name: 'pgsql'
    image: postgres:9.5
    environment:
      - POSTGRES_DB=yii2advanced
      - POSTGRES_USER=yii2advanced
      - POSTGRES_PASSWORD=secret
    ports:
      - "54322:5432"
   #volumes:
    #  - ${PGSQL_DATA_DIR-./data/pgsql}:/var/lib/postgresql/data
  redis:
    container_name: 'affilate-redis'
    image: redis:latest
    ports:
      - "${HOST_MACHINE_REDIS_PORT}:6379"
